version: '3.1'
services:
  mongo:
    build:
      context: ./mongo
      args:
        MONGO_VERSION: latest
    environment:
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27019
      MONGO_COMMAND: 'mongosh'
    ports:
      - '27019:27019'
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'mongosh', 'admin', '--port', '27019', '--eval', "db.adminCommand('ping').ok"]
      interval: 20s
      timeout: 2s
      retries: 5
    volumes: 
      - mongoreplica:/data/db

volumes:
  mongoreplica: